[package]
name = "seven2"
version = "0.1.0"
authors = ["Seth Yastrov <syastrov@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num_enum = "0.4.2"
permutohedron = "0.2.4"
